version: '3.6'

services:

  #Backend API
  smartbrain-backend:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smartbrain-backend
    environment:
      POSTGRES_URI: postgres://user:secret@postgres:5432/smartbrain-docker
    links: 
      - postgres
    ports: 
      - "3000:3000"
    volumes:
      - ./:/usr/src/smartbrain-backend

  #Postgres
  postgres:
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smartbrain-docker
      POSTGRES_HOST: postgres
     build: ./postgres
    ports:
      - "5432:5432"